### ISSUE TITLE
Trying to migrate CocoaPods-using project fails

### ISSUE THREAD

**Issue by a2** [lyptt/struct#17] opened 2017-03-10 20:40 UTC
I tried to migrate my project, which uses CocoaPods, and I think it's not understanding that the `Pods-<Project>.debug.xcconfig` file has a path relative to the parent `Pods` group which is not only its file name? I'm not sure though.

```
~/D/<Project> » bundle exec struct -m -p <Project>.xcodeproj -d .
bundler: failed to load command: struct (/Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/bin/struct)
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/a2/Developer/<Project>/Pods/Pods-<Project>.debug.xcconfig
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:1392:in `initialize'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
  /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/struct-1.1.0/lib/migrator/migrator.rb:104:in `block (2 levels) in migrate'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/struct-1.1.0/lib/migrator/migrator.rb:70:in `each'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/struct-1.1.0/lib/migrator/migrator.rb:70:in `block in migrate'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/struct-1.1.0/lib/migrator/migrator.rb:60:in `map'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/struct-1.1.0/lib/migrator/migrator.rb:60:in `migrate'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/struct-1.1.0/lib/binsupport/struct_bin.rb:142:in `do_migrate'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/struct-1.1.0/lib/binsupport/struct_bin.rb:38:in `block (2 levels) in run'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/slop-4.4.1/lib/slop/option.rb:60:in `ensure_call'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/slop-4.4.1/lib/slop/parser.rb:103:in `process'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/slop-4.4.1/lib/slop/parser.rb:110:in `try_process'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/slop-4.4.1/lib/slop/parser.rb:63:in `block in parse'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/slop-4.4.1/lib/slop/parser.rb:46:in `each'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/slop-4.4.1/lib/slop/parser.rb:46:in `each_with_index'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/slop-4.4.1/lib/slop/parser.rb:46:in `parse'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/slop-4.4.1/lib/slop/options.rb:71:in `parse'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/slop-4.4.1/lib/slop.rb:23:in `parse'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/struct-1.1.0/lib/binsupport/struct_bin.rb:24:in `run'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/gems/struct-1.1.0/bin/struct:4:in `<top (required)>'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/bin/struct:22:in `load'
  /Users/a2/Developer/<Project>/.bundle/ruby/2.3.0/bin/struct:22:in `<top (required)>'
~/D/<Project> » 
```

**Comment by lyptt** [comment] 2017-03-10 20:46
Hi @a2, thanks for filing this issue!

Unfortunately struct doesn't currently support CocoaPods, this issue is being tracked with #7. It's quite a complex issue to solve due the nature of CocoaPods rewiring projects when you `pod install`, but I'm confident I can get this working for the next major release.

In terms of this specific issue, I believe this is caused by the fact that CocoaPods build up Xcode projects in quite a unique manner. You can actually reproduce this by opening up the Xcode project rather than workspace, you'll notice Xcode can't resolve the location of the xcconfig files. Struct suffers the same limitations.

I'll add an issue in to go along with CocoaPods support to have a think about how we can approach CocoaPods with migration, it may be a simple case of just ignoring xcconfig files if they live within a pods directory.

What I'll also do is get a fix out for errors being thrown when xcconfig files are missing, as this should never happen.

**Comment by lyptt** [comment] 2017-03-10 21:40
Hi @a2, the error part of this issue is now fixed. Please track #7 for further developments on CocoaPods support. Thanks again for filing this issue!

**Closed** 2017-03-10 21:39 UTC
Labels: bug
